version: '3'

services:
  nasa-neows-api-data-extractor: # Descriptive service name
    container_name: nasa-neows-api-data-extractor-container # Meaningful container name
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - nasa-data-extractor-network

networks:
  nasa-data-extractor-network:
    driver: bridge